### ISSUE TITLE
404 Page 

### ISSUE THREAD

**Issue by SylviaZhaooo** [QuantEcon/continuous_time_mcs#104]
The page is not found when clicking the button of 'View Source'. @jstac 
<img width="1920" alt="Screenshot 2024-07-22 at 13 27 58" src="https://github.com/user-attachments/assets/36070e49-f2b1-40d7-a5c8-155700575c97">

**Comment by mmcky** [comment]
Thanks @jstac and @SylviaZhaooo -- this is now working as intended. 

Will implement https://github.com/QuantEcon/meta/issues/133 as a separate theme adjustment.
