### ISSUE TITLE
Notation Display Issue in Chrome and Edge

### ISSUE THREAD

**Issue by SylviaZhaooo** [QuantEcon/continuous_time_mcs#105]
Safari and Firefox look good.
<img width="1920" alt="Screenshot 2024-07-22 at 13 31 46" src="https://github.com/user-attachments/assets/3a08eb8e-d471-4da4-a910-639d72e6e346">

<img width="1920" alt="Screenshot 2024-07-22 at 13 33 39" src="https://github.com/user-attachments/assets/d746ca20-5dda-4bcf-94e5-4ed72f91f0eb">

But Chrome and Edge look bad.
<img width="1920" alt="Screenshot 2024-07-22 at 13 35 34" src="https://github.com/user-attachments/assets/784d7959-3ef6-4ad6-8720-d300c10ad5cf">
<img width="1920" alt="Screenshot 2024-07-22 at 13 36 29" src="https://github.com/user-attachments/assets/04bb09d8-797c-4ece-bf75-ad7c54b66796">

Pictures are put here in the same order following my statements.

**Comment by jstac** [comment]
@mmcky Some problem with Mathjax on Edge and Chrome?

**Comment by SylviaZhaooo** [comment]
@mmcky Thanks for the update. They all look good on my side.

**Comment by mmcky** [comment]
Great - thanks for confirming and reporting @SylviaZhaooo
