### ISSUE TITLE
Github Link directs to Old Github Directory 

### ISSUE THREAD

**Issue by HumphreyYang** [QuantEcon/continuous_time_mcs#106]
The "view source" bottom takes us to the old repo

 (i.e.,
https://github.com/jstac/continuous_time_mcs/tree/master/ctmc_lectures/kolmogorov_bwd.md
)

instead of the GitHub repo hosting the lecture.

**Comment by mmcky** [comment]
Thanks @HumphreyYang this is now fixed.
